### ISSUE TITLE
Investigate failing guides

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-guides#1066]
@timyates can you looking into these guides I had to skip: 

https://github.com/micronaut-projects/micronaut-guides/commit/bec0681fd75f8b90e13b7ecd928e1bc20be097b5

**Comment by timyates** [comment]
So I switched the Oracle guides round so that they use Test Resources for Kafka, and Oracle (the normal XE image, not the weird gitlab one with an unknown password)

However, the oracle Java and Kotlin tests seem to still be failing...

But only on Maven, they pass on Gradle 🙄 

The failure console log is here https://ge.micronaut.io/s/cyondppdp2lxi/console-log?page=6&task=:micronautOracleCloudStreamingRunTestScript#L5912

Seems to be no driver class name specified...  Which makes no sense to me...

@shingjo Could you take a look?

**Comment by sdelamo** [comment]
@timyates is this related or can be closed ? https://github.com/micronaut-projects/micronaut-guides/pull/1067

**Comment by timyates** [comment]
That's the linked PR where I was trying to fix the oracle test
